services:
  mongodb:
    image: mongo:8
    container_name: notely-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - notely_mongodb_data:/data/db

volumes:
  notely_mongodb_data:
